name: Build Docs
on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email toomore0929@gmail.com
            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true
            # ----- #0 By using worktree ----- #
            - name: Build Mkdocs
              run: |
                  git worktree add ./docs gh-pages
                  rm -rf ./docs/*
                  uv run mkdocs build -v -d ./docs
                  cd ./docs
                  git commit -a -m 'Deploy on ${{ github.ref_name }} ${{ github.sha }}'
                  git push origin HEAD
            # ----- #1 By using gh-deploy ----- #
            #- name: Build MkDocs
            #  run: |
            #      uv run mkdocs gh-deploy -b gh-pages -d ./docs -v --force
            # ----- #2 By Creating new branch and forcing to push ----- #
            #- name: Build MkDocs
            #  run: |
            #      uv run mkdocs build -d ./docs
            #      git checkout -b gh-pages main
            #      git add -f ./docs
            #      git commit -m 'Deploy MkDocs to GitHub Pages'
            #      git push -f origin gh-pages
